package persistence.sql.dialect;

import jakarta.persistence.GenerationType;

import java.sql.Types;
import java.util.Map;

public class H2Dialect implements Dialect {
    private final Map<Integer, String> mappingTable = Map.of(
            Types.BIGINT, "BIGINT",
            Types.VARCHAR, "VARCHAR",
            Types.INTEGER, "INTEGER"
    );

    private final Map<GenerationType, String> generationTypeMappingTable = Map.of(
            GenerationType.IDENTITY, "generated by default as identity"
    );

    @Override
    public String mapDataType(int type) {
        String str = mappingTable.get(type);
        if (str == null) {
            throw new IllegalArgumentException("지원하지 않는 타입입니다.");
        }
        return str;
    }

    @Override
    public String mapGenerationType(GenerationType strategy) {
        String str = generationTypeMappingTable.get(strategy);
        if (str == null) {
            throw new IllegalArgumentException("지원하지 않는 전략입니다.");
        }
        return str;
    }

    @Override
    public String getGeneratedIdSelectQuery() {
        return "CALL IDENTITY()";
    }
}
