package persistence.entity;

import database.Database;
import database.DatabaseServer;
import database.H2;
import database.SimpleDatabase;
import jdbc.JdbcTemplate;
import org.junit.jupiter.api.*;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;
import persistence.sql.ddl.DDLQueryBuilder;
import persistence.sql.dialect.Dialect;
import persistence.sql.dialect.H2Dialect;
import persistence.sql.dml.DMLQueryBuilder;
import persistence.sql.model.Table;
import persistence.study.sql.ddl.Order;
import persistence.study.sql.ddl.OrderItem;
import persistence.study.sql.ddl.Person3;

import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Stream;

import static org.assertj.core.api.Assertions.assertThat;

public class EntityLoaderTest {

    private static DatabaseServer server;
    private static JdbcTemplate jdbcTemplate;
    private static EntityLoader loader;

    private static DDLQueryBuilder ddlQueryBuilder;
    private static DMLQueryBuilder dmlQueryBuilder;

    @BeforeAll
    static void initialize() throws SQLException {
        server = new H2();
        server.start();

        Connection jdbcConnection = server.getConnection();
        jdbcTemplate = new JdbcTemplate(jdbcConnection);

        Database database = new SimpleDatabase(jdbcTemplate);
        loader = new EntityLoader(database);

        Dialect dialect = new H2Dialect();
        Table table = new Table(Person3.class);
        ddlQueryBuilder = new DDLQueryBuilder(table, dialect);
        dmlQueryBuilder = new DMLQueryBuilder(table);
    }

    @AfterAll
    static void close() {
        server.stop();
    }

    @BeforeEach
    void setUp() {
        String createTableQuery = ddlQueryBuilder.buildCreateQuery();
        jdbcTemplate.execute(createTableQuery);

        jdbcTemplate.execute("CREATE TABLE orders (id bigint generated by default as identity default on null primary key,order_number varchar)");
        jdbcTemplate.execute("CREATE TABLE order_items (id bigint generated by default as identity default on null primary key,product varchar,quantity integer,order_id bigint,FOREIGN KEY(order_id) REFERENCES orders(id) ON UPDATE CASCADE)");

        Stream<Person3> persons = createPersons();
        persons.forEach(person -> {
            String insertQuery = dmlQueryBuilder.buildInsertQuery(person);
            jdbcTemplate.execute(insertQuery);
        });

        jdbcTemplate.execute("INSERT INTO orders (id, order_number) VALUES (null, '오더 넘버')");
        jdbcTemplate.execute("INSERT INTO order_items (id, product, quantity, order_id) VALUES (null, 'abc', 123, 1)");
        jdbcTemplate.execute("INSERT INTO order_items (id, product, quantity, order_id) VALUES (null, 'def', 456, 1)");
    }

    private Stream<Person3> createPersons() {
        return Stream.of(
                new Person3("qwer1", 1, "email1@email.com"),
                new Person3("qwer2", 2, "email2@email.com"),
                new Person3("qwer3", 3, "email3@email.com")
        );
    }

    @AfterEach
    void setDown() {
        String dropQuery = ddlQueryBuilder.buildDropQuery();
        jdbcTemplate.execute(dropQuery);

        jdbcTemplate.execute("DROP TABLE orders, order_items");
    }

    @Test
    @DisplayName("person을 이용하여 read 메서드 테스트")
    void read() {
        EntityId id = new EntityId(3L);
        Person3 result = loader.read(Person3.class, id);

        Person3 expect = new Person3(3L, "qwer3", 3, "email3@email.com");
        assertThat(result).isEqualTo(expect);
    }

    @ParameterizedTest
    @MethodSource
    @DisplayName("person을 이용하여 isExist 메서드 테스트")
    void isExist(Person3 person, boolean expect) {
        boolean result = loader.isExist(person);

        assertThat(result).isEqualTo(expect);
    }

    private static Stream<Arguments> isExist() {
        return Stream.of(
                Arguments.arguments(new Person3(1L, "qwer3", 3, "email3@email.com"), true),
                Arguments.arguments(new Person3(5L, "qwer3", 3, "email3@email.com"), false)
        );
    }

    @Test
    @DisplayName("Order 를 이용하여 join 쿼리로 연관관계 엔티티까지 가져오기")
    void readWithJoin() {
        EntityId id = new EntityId(1L);

        Order result = loader.read(Order.class, id);

        Order expect = createOrder();
        assertThat(result).isEqualTo(expect);
    }

    private Order createOrder() {
        List<OrderItem> orderItems = new ArrayList<>();
        orderItems.add(new OrderItem(1L, "abc", 123));
        orderItems.add(new OrderItem(2L, "def", 456));
        return new Order(1L, "오더 넘버", orderItems);
    }
}
