package domain.helper;

import domain.Order;
import domain.OrderItem;

public class CreateSqlHelper {
    public static String orderCreateSql() {
        return "create table orders (\n" +
                "       id bigint generated by default as identity,\n" +
                "        order_number varchar(255),\n" +
                "        primary key (id)\n" +
                "    )";
    }

    public static String orderItemCreateSql() {
        return "create table order_items (\n" +
                "       id bigint generated by default as identity,\n" +
                "        product varchar(255),\n" +
                "        quantity integer,\n" +
                "        order_id bigint,\n" +
                "        primary key (id)\n" +
                "    )";
    }

    public static String 주문을_생성하는_쿼리_생성(Order order) {
        return String.format("INSERT INTO orders (id, order_number) VALUES(%d, %s)", order.getId(), order.getOrderNumber());
    }

    public static String 주문아이템을_생성하는_쿼리_생성(OrderItem item, Order order) {
        return String.format("INSERT INTO order_items (id, product, quantity, order_id) VALUES(%d, '%s', %d, %d)", item.getId(), item.getProduct(), item.getQuantity(), order.getId());
    }
}
